[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Packages already installed in install phase'"]

[start]
cmd = "cd backend/api && uvicorn main:app --host 0.0.0.0 --port $PORT"
