[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r backend/requirements.txt"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "cd backend/api && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
